# Generated by Django 2.2 on 2021-09-20 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userregistrationmodel',
            name='status',
            field=models.CharField(default='waiting', max_length=100),
        ),
    ]
